FROM apache/nifi:1.27.0

# Passer en mode root pour installer les paquets
USER root

# Mettre à jour les paquets et installer Python3 + pip
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    apt-get clean

# Revenir à l'utilisateur NiFi
USER nifi

